version: '3.9'
services:
  test-app:
    build: .
    command: ["uvicorn", "src.main:app", "--port", "8010", "--host", "0.0.0.0"]
    ports: [9012:8010]
    restart: always
    environment:
      DB_NAME: 'testdb'
      DB_USER: 'postgres'
      DB_PASSWD: 'qwerty1234'
      DB_HOST: 'db'
      BACKEND_CORS_ORIGINS: '*'

  db:
    image: postgres:alpine
    ports: [5432:5432]
    restart: always
    environment:
      POSTGRES_DB: 'testdb'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'qwerty1234'
    volumes:
      - ./test_db.sql:/docker-entrypoint-initdb.d/init_db.sql
